name: Ubuntu

on:
  push:
    branches: [ "master", "dev" , "gh_actions" ]
  pull_request:
  workflow_dispatch: 

jobs:
  build-and-test:
    name: Build for Ubuntu
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            meson ninja-build pkg-config \
            gcc clang \
            lua5.4 liblua5.4-dev \
            libjson-c-dev \
            libcurl4-openssl-dev \
            libunibilium-dev \
            libserialport-dev \
            libssh2-1-dev \
            libgpg-error-dev
      - name: Build & Install
        run: |
          meson setup build -Dbuildtype=release -Dltf_dir_path="$PWD"
          meson compile -C build
          ./build/ltf --version

      - name: Self-Tests
        id: run_test
        run: |
          cd selftest
          set +e
          modules=(http json proc ltf webdriver util)
          FAILED=0

          for m in "${modules[@]}"; do
            echo "::group::module-$m"
            ../build/ltf test selftest -t module-"$m" -e -v any=anyval,enum=value2
            STATUS=$?
            echo "::endgroup::"

            mkdir -p logs/ci/bootstrap logs/ci/selftest
            cp -L logs/bootstrap/test_run_latest_raw.json     logs/ci/bootstrap/${m}-raw.json     || true
            cp -L logs/bootstrap/test_run_latest_output.log   logs/ci/bootstrap/${m}-output.log   || true
            cp -L logs/selftest/test_run_latest_raw.json      logs/ci/selftest/${m}-raw.json      || true
            cp -L logs/selftest/test_run_latest_output.log    logs/ci/selftest/${m}-output.log    || true

            if [ $STATUS -ne 0 ]; then
              FAILED=1
            fi
          done
          exit $FAILED

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selftest-logs
          path: selftest/logs/ci

  docs:
    name: Docs Build and Deploy
    needs: build-and-test 
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com name: Build and Deploy Docs
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache 


          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 


      - run: mkdocs gh-deploy --force


