name: Ubuntu

on:
  push:
    branches: [ "master", "gh_actions" ]
  pull_request:
  workflow_dispatch: 

jobs:
  build-and-test:
    name: Build for Ubuntu
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install meson curl json-c lua libserialport libunistring libssh2 unibilium chromedriver google-chrome

      - name: Build & Install
        run: |
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          export PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/lib/pkgconfig:/home/linuxbrew/.linuxbrew/share/pkgconfig"
          meson setup build
          meson install -C build

      - name: Self-Tests
        id: run_test
        run: |
          cd selftest
          set +e
          modules=(http json proc ltf webdriver)
          FAILED=0

          for m in "${modules[@]}"; do
            echo "::group::module-$m"
            ltf test selftest -t module-"$m" -e
            STATUS=$?
            echo "::endgroup::"

            mkdir -p logs/ci/bootstrap logs/ci/selftest
            cp -L logs/bootstrap/test_run_latest_raw.json     logs/ci/bootstrap/${m}-raw.json     || true
            cp -L logs/bootstrap/test_run_latest_output.log   logs/ci/bootstrap/${m}-output.log   || true
            cp -L logs/selftest/test_run_latest_raw.json      logs/ci/selftest/${m}-raw.json      || true
            cp -L logs/selftest/test_run_latest_output.log    logs/ci/selftest/${m}-output.log    || true

            if [ $STATUS -ne 0 ]; then
              FAILED=1
            fi
          done
          exit $FAILED

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selftest-logs
          path: selftest/logs/ci

  docs:
    name: Docs Build and Deploy
    needs: build-and-test 
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build and Deploy Docs
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install mkdocs mkdocs-material
          mkdocs gh-deploy



